name: "vuepress-build"

on:
  push:
    branches: [master]
    paths:
    - '.github/**'
    - 'docs/**'
    - .spelling
    - package.json
    - package-lock.json

env:
  EXCLUDE_WEB_PAGES: "(myexample.dev|mylabs.dev|https://github.com/ruzickap/k8s-flux-repository)"

jobs:
  markdown-lint-check:
    name: "Markdown lint check"
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: "Install Node.js 12"
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: "Install markdownlint-cli"
      run: npm install -g markdownlint-cli

    - name: "Create markdownlint configuration file"
      run: |
        echo "{ MD013: { code_blocks: false } }" > /tmp/markdownlint_config.json

    - name: "Run markdownlint"
      run: find . -path ./node_modules -prune -o -name "*.md" -print0 | xargs -t -0 markdownlint -c /tmp/markdownlint_config.json

  markdown-spell-check:
    name: "Markdown spell check"
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: "Install Node.js 12"
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: "Install markdown-spellcheck"
      run: npm install -g markdown-spellcheck

    - name: "Run mdspell"
      run: mdspell '**/*.md' '!**/node_modules/**/*.md' --ignore-numbers --ignore-acronyms --report --en-gb

  vuepress-build:
    name: "VuePress build"
    runs-on: ubuntu-18.04
    needs:
      - markdown-lint-check
      - markdown-spell-check

    steps:
    - uses: actions/checkout@v1

    - name: "Install Node.js 12"
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: "Install VuePress and build the document"
      run: |
        npm install
        npm run build
        cp LICENSE docs/.vuepress/dist
        ln -s docs/.vuepress/dist ${GITHUB_REPOSITORY##*/}
        sed -e "s@(part-@(https://github.com/${GITHUB_REPOSITORY}/tree/master/docs/part-@" -e 's@.\/.vuepress\/public\/@./@' docs/README.md > docs/.vuepress/dist/README.md
        touch docs/.vuepress/dist/.nojekyll

    - name: "Check links"
      run: |
        echo "127.0.0.1 ${GITHUB_REPOSITORY%/*}.github.io" | sudo tee -a /etc/hosts
        curl -s https://getcaddy.com | bash -s personal
        cat > Caddyfile << EOF
        https://${GITHUB_REPOSITORY%/*}.github.io
        tls self_signed
        EOF
        sudo caddy -quiet &
        go get -u github.com/raviqqe/muffet
        ~/go/bin/muffet --skip-tls-verification --exclude "${EXCLUDE_WEB_PAGES}" https://${GITHUB_REPOSITORY%/*}.github.io/${GITHUB_REPOSITORY##*/}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs/.vuepress/dist
      with:
        emptyCommits: false
        forceOrphan: true
